.github/workflows/auto-pr.yml

This secret doesn't exist yet, but it will eventually.

workflows/auto-pr: forward HOMEBREW_GITHUB_API_TOKEN from secrets to env

---

pip-audit-bulk

Makes it easily extensible if we have more, and adds an explanatory comment.

Better organize how we ignore vulns

---

README.md

Signed-off-by: William Woodruff <william@yossarian.net>

README: reflow, docs

---

formula2requirements.rb
generate-prs.rb
pip-audit-bulk

This makes it easy to assess progress

Sort formula processing in scripts

---

formula2requirements.rb

formula2requirements: blow away old requirements

---

generate-prs.rb

And attempt to generate a PR for flintrock.

Re-add support for generating PRs only for known formula

---

generate-prs.rb

Slowly ease our way into turning this back on

Remove formula restriction but lower pr limit

---

.github/workflows/auto-pr.yml

See https://github.com/Homebrew/brew/pull/15307.

auto-pr: remove pipgrip

---

.github/workflows/auto-pr.yml

...this should use `master`, as we expect. Will test now.

auto-pr: switch to setup-homebrew action

---

.github/workflows/auto-pr.yml
generate-prs.rb

More debugging is always more better.

generate-prs: more debugging

---

generate-prs.rb

This all appears to be working now

generate-prs: increase PR limit

---

generate-prs.rb

generate-prs: remove ping req

---

.github/workflows/auto-pr.yml

This _may_ be causing our PAT pains.

auto-pr: drop HOMEBREW_NO_AUTO_UPDATE

---

.github/workflows/auto-pr.yml

Should speed the `auto-pr` workflow up a bit.

Cleanup, cache bundler gems

---

.github/workflows/auto-pr.yml

See: https://github.com/Homebrew/brew/blob/6170b6297c61ef0b68814c708eeff2199d8b0d11/.github/workflows/tests.yml#L353

auto-pr: fix broken runner python

---

generate-prs.rb

See https://github.com/Homebrew/brew/commit/7df07b991b2d89b8e36fbbde678ae0249c437646

Update for change to brew API

---

generate-prs.rb

relates to https://github.com/Homebrew/brew/pull/18388

chore: tap.remote_repo -> tap.remote_repository

---

.github/workflows/audit.yml

https://github.com/Homebrew/brew-pip-audit/actions/runs/11269866397/job/31339360590

Use --force with untap

---

generate-prs.rb

fixes https://github.com/Homebrew/brew-pip-audit/issues/128
relates to:
- https://github.com/Homebrew/homebrew-core/pull/197793
- https://github.com/Homebrew/homebrew-core/pull/197983
cc @daeho-ro @woodruffw

chore: ignore ansible-lint

---

generate-prs.rb

Unclear if this fixes things.
Carbon-copied from https://github.com/Homebrew/brew/blob/83e4d736706b0020a32c109d748fc424dce25c23/Library/Homebrew/dev-cmd/bump-cask-pr.rb#L162-L172

add pr_title

---

generate-prs.rb

use strict: true when checking for duplicate PRs

---

generate-prs.rb

charmcraft autobump issue has been resolved for quite some time https://github.com/Homebrew/homebrew-core/pull/226765, so bring the track back.
- https://github.com/Homebrew/homebrew-core/pull/227737

track charmcraft again
