Homebrew/brew-pip-audit

.github/workflows/auto-pr.yml
The `brew-pip-audit` PRs in `homebrew-core` have the `git` author and committer set to `runner`. This PR modifies the `auto-pr` workflow to use the `git-user-config` action, so the PR commits will now be authored by `BrewTestBot`.
=> auto-pr: configure `git` user

.github/workflows/auto-pr.yml, generate-prs.rb
Disables buffered stdout to prevent confusing ordering between stdout and stderr lines; adds more context to individual logs.
=> generate-prs: better logging

.github/workflows/auto-pr.yml, generate-prs.rb
This ensures that these patches land with users on the formula's current version, not the next time they upgrade.
Closes #19.
=> generate-prs: bump revision with PRs

generate-prs.rb
To help the triage task auto-label us correctly.
Closes #60.
=> generate-prs: no link in body

generate-prs.rb
I helped the `theharvester` correctly define their dependencies in https://github.com/laramies/theHarvester/pull/1505, so after https://github.com/Homebrew/homebrew-core/pull/157756 this is no longer a special case that needs to be skipped
=> generate-prs: remove theharvester from `SKIP_FORMULA`

generate-prs.rb
Noticed these are fixed.
`jenkins-job-builder`: The pin for `setuptools` was removed in https://opendev.org/jjb/jenkins-job-builder/commit/67645a46ebaf29d0447049d8b40f39fef31bfb70
`fdroidserver`: @alex's PR was merged and both `pipgrip` and `brew update-python-resources` point to v4.0.2 of `androguard`.
=> generate-prs: remove fixed formulae from `SKIP_FORMULA`

generate-prs.rb
Should be possible now that https://github.com/Homebrew/brew/pull/16753 is landed
=> Allow bumping several new packages

generate-prs.rb
This doesn't fix anything, but will hopefully give us more insight into why `pytorch` hangs while updating.
=> generate-prs: be more verbose while updating

.github/workflows/auto-pr.yml
`pytorch` is causing a CI timeout, almost certainly because of a chonky sdist build. This attempts to ignore the problem of terrible build times by increasing our timeout to an even more unreasonable number.
If it still times out with this, I'll revert and put `pytorch` on the ignore list instead.
=> auto-pr: double the timeout

generate-prs.rb
The pytorch sdist build takes up a significant portion of our PR generation run time while trying to build an absolute beast of a C++ monolith from source and finally failing with some kind of `git` error ([link](https://github.com/Homebrew/brew-pip-audit/actions/runs/9926463368/job/27420096899#step:10:8149)).
Current hypothesis is that this is their own homegrown version of the `setuptools_scm` archive problem, meaning that we can't easily address it using the GitHub release artifact.
=> generate-prs: skip pytorch

.github/workflows/audit.yml, .github/workflows/auto-pr.yml
In particular, this replaces `auto-pr`'s `workflow_run` with a `workflow_call`, turning it into a reusable workflow.
=> workflows: fix zizmor issues

.github/workflows/auto-pr.yml
Now that we use `workflow_call`, we don't need to check for success.
=> Remove conditional in auto-pr.yml

.github/workflows/actionlint.yml, .github/workflows/audit.yml, .github/workflows/auto-pr.yml
This is consistent with what we are doing with https://github.com/Homebrew/brew/pull/17691
> Pin the version of the actions to full length commit SHA as described in the [security hardening for GitHub Actions guide](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).
=> feat: pin workflow action sha

.github/workflows/audit.yml, .github/workflows/auto-pr.yml
This helps with transparency and they get updated by Dependabot.
=> workflows: use full version numbers

generate-prs.rb
currently the ast tree rewrite has some issue, this is the patch to fix it for formula like systemd, we can move this logic into `Library/Homebrew/utils/ast.rb` after runs out fine.
=> fix: patch revision bump issue

.github/workflows/audit.yml, .github/workflows/auto-pr.yml
Now that we've removed all the GPG code, this is a no-op.
=> workflows: remove no-op ssh signing value

.github/workflows/audit.yml, .gitignore, formula2requirements.rb, generate-prs.rb, pip-audit-bulk, site/index.md
Still a work in progress.
The basic idea here:
1. Create a stub website under `site/`
2. Update our requirements/audit generation tooling to dump JSON files under `site/`
3. Update the PR-filing tooling to read from `https://homebrew.github.io/brew-pip-audit` instead of repo state
4. ???
5. Profit
Aa part of this, the `audit.yml` workflow will also need to change to a pages-publishing workflow.
Closes #84.
=> refactor: move to a pages-based setup

formula2requirements.rb
Potential fix for [https://github.com/Homebrew/brew-pip-audit/security/code-scanning/24](https://github.com/Homebrew/brew-pip-audit/security/code-scanning/24)
To fix the problem, the regular expression should be anchored so that it matches only URLs where "files.pythonhosted.org" appears in the correct location (the host portion). Since the code is working with URLs, the best way is to parse the URL and check the host directly, rather than matching the entire URL string with a regular expression. This avoids any ambiguity and ensures only the intended host is matched. The fix should be applied to line 18 in `formula2requirements.rb`, replacing the regular expression match with a check on the parsed host.
No new imports are needed, as `URI` is already required.
_Suggested fixes powered by …
=> Potential fix for code scanning alert no. 24: Missing regular expression anchor

generate-prs.rb
Potential fix for [https://github.com/Homebrew/brew-pip-audit/security/code-scanning/22](https://github.com/Homebrew/brew-pip-audit/security/code-scanning/22)
To fix the problem, the regular expression should be anchored so that it matches only URLs whose host is exactly "files.pythonhosted.org". In Ruby, the recommended anchors for the start and end of a string are `\A` and `\z`, not `^` and `$`, to avoid issues with newlines. The best fix is to update the regular expression in line 141 to use `\Ahttps?:\/\/files\.pythonhosted\.org\/`, which will match only URLs that start with "http://" or "https://" and then "files.pythonhosted.org/". This change should be made only in the relevant line in `generate-prs.rb`. No new imports or methods are needed.
_Suggested fixes powered by Copilot …
=> Potential fix for code scanning alert no. 22: Missing regular expression anchor

generate-prs.rb
Potential fix for [https://github.com/Homebrew/brew-pip-audit/security/code-scanning/23](https://github.com/Homebrew/brew-pip-audit/security/code-scanning/23)
To fix the problem, the regular expression should be anchored so that it matches only when "files.pythonhosted.org" appears at the start of the host portion of the URL. In Ruby, the best way to do this is to use the `\A` anchor to match the start of the string, and to include the URL scheme and host in the pattern. For example, the pattern should match URLs that start with "http://" or "https://" followed immediately by "files.pythonhosted.org". The updated regular expression would be `/\Ahttps?:\/\/files\.pythonhosted\.org\//`. This change should be made on line 170 of `generate-prs.rb`, replacing the unanchored pattern.
--- …
=> Potential fix for code scanning alert no. 23: Missing regular expression anchor

.github/workflows/audit.yml, .github/workflows/auto-pr.yml
`test-bot` has been merged into Homebrew/brew, so this is no longer necessary and outputs a warning in CI.
---
- https://github.com/Homebrew/brew/pull/20762
=> workflows: remove `test-bot` Action inputs
